# Generated by Django 5.2 on 2025-09-04 07:43

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_article_file_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=myapp.models.book_pdf_upload_to),
        ),
    ]
